// <auto-generated />
using System;
using Liceu.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Liceu.WebApp.Migrations.LiceuDb
{
    [DbContext(typeof(LiceuDbContext))]
    [Migration("20190209014659_Liceu")]
    partial class Liceu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Liceu.Dominio.Entidades.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano")
                        .HasColumnName("ANO_LANCAMENTO")
                        .HasMaxLength(4);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnName("NOME_AUTOR")
                        .HasMaxLength(30);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnName("NOME_EDITORA")
                        .HasMaxLength(50);

                    b.Property<int>("Status")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("TITULO")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("GE_LIVRO");
                });
#pragma warning restore 612, 618
        }
    }
}
